- linux-sandbox.jl/common.jl
This allows files in `TMPDIR` to appear in the same place on the host
as within the sandbox, allowing for `docker build --ssh default` to
work properly, since it places files in `TMPDIR` and expects to be able
to mount them in.
> When running with docker, add stable mountpoint for TMPDIR

- common/buildkite_config.jl
- hooks/environment.d/101_julia_num_cores.sh
- hooks/environment.d/999_cryptic_unlock.sh
- linux-sandbox.jl/.gitignore
- linux-sandbox.jl/common.jl
- linux-sandbox.jl/config.toml.example
- macos-seatbelt/.gitignore
- macos-seatbelt/Artifacts.toml
- macos-seatbelt/MacOSSandboxConfig.jl
- macos-seatbelt/Manifest.toml
- macos-seatbelt/Project.toml
- macos-seatbelt/common.jl
- macos-seatbelt/config.toml.example
- macos-seatbelt/debug_shell.jl
- macos-seatbelt/launch_agents.jl
- macos-seatbelt/uninstall_agents.jl
This PR adds a macOS runner that makes use of the macOS sandbox functionality known as Seatbelt to reduce the harm a malicious CI job could do to one of our machines.  It also allows for secrets management by allowing secrets to be stored in an unreadable location, then having the CI start job copy secrets into a readable location, but having an agent environment hook delete them if the job is not privileged, similar to how the `sandbox.jl` runner unmounts the secrets location.
> Add macOS support

- Manifest.toml
- common/buildkite_config.jl
- common/linux_systemd_config.jl
- linux-sandbox.jl/cgroup_wrapper.sh
- linux-sandbox.jl/common.jl
- linux-sandbox.jl/debug_shell.jl
- linux-sandbox.jl/launch_agents.jl
- linux-sandbox.jl/mk_cgroup.c
- macos-seatbelt/common.jl
- windows-kvm/buildkite-worker/common.jl
- windows-kvm/buildkite-worker/setup_scripts/0-02-install-buildkite-agent.ps1
This builds cgroups with pinned cores, for better worker isolation (and
to teach `rr` to not always pin to the same first few CPUs).  This is
implemented by creating wrapper scripts that generate cgroups and pin
agents to specific cores.  This has the added benefit of completely
disallowing a poorly-behaved worker process from taking over other
worker's cores.
> Add `num_cpus` config option

- common/buildkite_config.jl
- common/mac_seatbelt_config.jl
- linux-sandbox.jl/common.jl
- macos-seatbelt/common.jl
Initial usecase: dodging socket pathname limits on macOS.  It turns out
that libuv doesn't support pathnames larger than 108, which is much
smalelr than the `bind()` syscall actually supports.
> Add `tempdir` to allow overriding `TMPDIR` on a per-BRG basis

- hooks/environment.d/101_julia_num_cores.sh
This allows us to use only performance cores on big.LITTLE architectures like the Apple M1
> Improve `nproc` shim for macOS

- Manifest.toml
- Project.toml
- common/common.jl
- common/linux_coredump_config.jl
- linux-sandbox.jl/common.jl
This will give us intelligent names for coredumps that occur during
testing.  We'll use this with improvments to our testing scripts to
automatically dump out useful information and upload full core dumps.
> Add automatic checks for coredump patterning

- common/common.jl
- common/linux_systemd_config.jl
- linux-sandbox.jl/common.jl
- linux-sandbox.jl/debug_shell.jl
- macos-seatbelt/common.jl
- windows-kvm/buildkite-worker/common.jl
Motivated by `armageddon.julialang.org` being set as a hostname; we
really only want `armageddon`.
> Use short hostname

- common/linux_systemd_config.jl
- linux-sandbox.jl/common.jl
This will allow us to gracefully stop our buildkite-agent processes,
instead of brutally murdering them and interrupting jobs every time we
have a new configuration change.  This will send `SIGTERM` to the
sandbox process, and then wait up to two hours before sending a
`SIGKILL` to the entire process group.
For this to actually work, we need to wait until sandbox responds to
signals properly, which is pending this PR [0] getting merged.
[0] https://github.com/staticfloat/Sandbox.jl/pull/90
> Add `stop_timeout` and apply it to 120min

- common/linux_coredump_config.jl
- linux-sandbox.jl/common.jl
We need to disable `apport` and ensure that our core dump naming pattern
is listed as a sysctl parameter so it survives reboots.
> Ensure coredump patterns survive a reboot

- macos-seatbelt/common.jl
We can't use the `agent-shutdown` hook like we do for our windows machines, since we run in a sandbox that disallows calling `sudo` from within the sandbox in the first place.
> Auto-reboot macOS agents after 24 hours

- windows-kvm/debug/.gitignore
I guess we'll acquiesce to `git`'s feelings on this matter.
> Git v2.32+ doesn't like `.gitignore` symlinks

- hooks/environment
- hooks/environment.d/100_gr_env.sh
- hooks/environment.d/101_julia_num_cores.sh
- hooks/environment.d/999_cryptic_unlock.sh
The `nproc` bit should hopefully fix the failure in my julia-buildkite PR.
> Define `nproc` on FreeBSD and use `/usr/bin/env bash` in shebangs

- freebsd-kvm/buildkite-worker/setup_scripts/install-buildkite-agent.sh
- windows-kvm/buildkite-worker/setup_scripts/0-00-format-data-disk.ps1
- windows-kvm/buildkite-worker/setup_scripts/0-02-install-buildkite-agent.ps1
- windows-kvm/buildkite-worker/setup_scripts/0-06-set-docker-dataroot.ps1
This one took down our Windows workers for almost a day.  Let me tell
you a story about Windows, Docker, and naive sysadmins (me):
Once upon a time, little old staticfloat thought that he would be able
to easily mirror (pun intended) the `git-mirrors` configuration used on
the Linux, macOS and now FreeBSD workers on the Windows workers as well.
He dutifully copied over the relevant buildkite-agent configuration,
setup a folder within the cache disk `Z:` to hold the cached git clones,
and started up the agent.  The agent booted up just fine, but then he
saw a most peculiar error:
```
docker: Error response from daemon: hcsshim::CreateComputeSystem e56f18be8cf3dd0b0f751bc305f9e8faa358a66e6daca844e17888d3a17ed63b: The parameter is incorrect.
```
A quick google around made it sound like …
> Include experimental features on Windows as well

- windows-kvm/buildkite-worker/setup_scripts/0-02-install-buildkite-agent.ps1
This causes the "git mirrors" experiment, which uses a local cache of the repositories used in the build process to now create a standalone clone in the build directory.  This is more disk traffic, but it breaks the link between the build directory and the cache directory where the git repository is stored.  This is necessary because I recently added a better way of mounting the cache disk, but `git` seems to normalize the path to the cache disk in an odd way, finding it moutned at `Z:` (which is true) instead of the file path given to it, at `C:\cache` (which is also true).  This causes problems inside of docker, where there is only `C:\cache`.
An alternative to this is to manually overwrite
`.git/objects/info/alternates` with `C:\cache\...`, but that feels a little bit dirtier.
> Add `--dissociate` to windows git clone flags

- freebsd-kvm/base-image/setup_scripts/user.sh
- freebsd-kvm/buildkite-worker/setup_scripts/install-buildkite-agent.sh
The approach:
- Allow the user to reboot without root permissions by adding them to the `operator` group
- Rather than reusing the [provided rc.d script](https://cgit.freebsd.org/ports/tree/devel/buildkite-agent/files/buildkite.in) from the [buildkite-agent port](https://www.freshports.org/devel/buildkite-agent/), we can cowboy our own by skimming the FreeBSD [article](https://docs.freebsd.org/en/articles/rc-scripting/) on rc.d scripting and making something that looks plausibly correct
- Set the command that gets run at service start to invoke `buildkite-agent start` then `shutdown -r now`
- Set the `buildkite_user` variable so that the service's command is run as the specified user
Will this work as intended? Who knows!
> FreeBSD: Reboot after the buildkite job finishes

- windows-kvm/buildkite-worker/setup_scripts/0-02-install-buildkite-agent.ps1
For some reason, we seem to keep on getting Windows machines picking up jobs before they restart; let's see if increasing the restart delay works.
> Try another fix to windows workers not restarting

- common/buildkite_config.jl
- hooks/environment.d/500_windows_debugging.sh
- linux-sandbox.jl/common.jl
This allows overriding the cache files via the `cachedir` directive in the `config.toml`.  You can even assign two different BRGs with two different cache directories, to split workers across two disks, for instance.
> Store build cache in a per-BRG configurable cache directory

- windows-kvm/buildkite-worker/common.jl
Now that https://github.com/JuliaLang/julia/pull/47803 has been merged, we are using [significantly less commit charge](https://github.com/JuliaLang/julia/pull/47803#issuecomment-1338053358), and should be capable of running with only 3GB/core allocated, rather than the currently rather wasteful 4GB/core.
> Reduce Windows VM memory allocation to 3GB/core

- freebsd-kvm/buildkite-worker/setup_scripts/install-buildkite-agent.sh
According to a [discussion on the FreeBSD forum](https://forums.freebsd.org/threads/how-to-run-rc-d-service-as-specific-user.86879/), the specified user may not actually be the one who owns the `buildkite-agent` process. While buildkite seems to be configured to run jobs as said user, there seems to be some kind of configuration mismatch since the Julia tests claim they're being run as root (see test log in https://github.com/JuliaCI/julia-buildkite/pull/266). We can try to fix this by wrapping the command to launch `buildkite-agent` in `su`.
> [freebsd-kvm] Wrap the rc.d buildkite-agent invocation in `su`

- freebsd-kvm/buildkite-worker/kvm_machine.pkr.hcl.template
- freebsd-kvm/buildkite-worker/setup_scripts/install-more-dependencies.sh
- freebsd-kvm/buildkite-worker/setup_scripts/install-zstd.sh
This ensures that `gpg` and `gpgconf` are available in the buildkite worker image for tarball signing (see job failure in https://github.com/JuliaCI/julia-buildkite/pull/266)
> Rename `install-zstd.sh` and also install GnuPG

- freebsd-kvm/buildkite-worker/setup_scripts/install-buildkite-agent.sh
It seems that when the `buildkite-agent` process exits with a nonzero code, the `buildkite_start` function in the rc.d script returns before it gets to `shutdown`. This leaves VMs with failed jobs just sitting around, since `buildkite-agent` is no longer running and nothing else is there to shut them down.
That's our working hypothesis, anyway. I attempted to test it by making this change locally on a worker and manually restarting the `buildkite` service. The job it picked up finished successfully so this didn't really get tested, but at least it didn't break anything.
> [freebsd-kvm] Ignore nonzero exits from `buildkite-agent`

- windows-kvm/base-image/setup_scripts/2-03-install-git.ps1
- windows-kvm/debug/setup_scripts/0-10-install-julia.ps1
Turns out that `--system` is less than ideal if a pipeline can bring its own `git.exe`.
> Fix windows long paths (again)

- freebsd-kvm/buildkite-worker/setup_scripts/install-buildkite-agent.sh
Unfortunately, our FreeBSD agents seem to have a hard time cloning with `--mirror`, something about the request borks github and we end up timing out, or getting a bad response, or something.  By disabling the `--mirror` optimization, we are able to get things working.  I suppose we'll try turning it on again in the future.  This used to work in FreeBSD 12, so I suspect something like libcurl v8.1 is causing an issue here.
> Lock to buildkite agent v3.39.0 on FreeBSD, and disable git-mirrors

- hooks/environment.d/500_windows_debugging.sh
Hopefully, Gabriel's PR [0] will have fixed the issues we were seeing, and in any case, nobody was looking at this debugging information recently, so let's just drop it and clean up our build logs.
[0] https://github.com/JuliaCI/julia-buildkite/pull/361
> Disable windows debugging for now

- linux-sandbox.jl/common.jl
This should give our workers a chance to perform final cleanup such as uploading core files and such.  A little annoying that I have to enable this globally rather than on a pipeline-by-pipeline basis, but c'est la vie.
> Set Linux cancellation grace period to 5 minutes

- freebsd-kvm/buildkite-worker/kvm_machine.pkr.hcl.template
- freebsd-kvm/buildkite-worker/setup_scripts/configure-dns-resolver.sh
We've been experiencing a failure in Julia's Downloads tests on FreeBSD, reproducible only in our VMs: the request to `https://domain.invalid` hits the 30-second timeout set by default in Downloads because it takes a full 30 seconds for the resolver to report `NXDOMAIN`. I have no idea why, and I can't even reproduce it in a FreeBSD VM on my local machine. Absent a real fix, we can apply a band-aid in the meantime: prefer Google's nameserver in the DNS resolver configuration. In the debugging VM on amdci6, this allows the Downloads tests to pass succesfully.
> Reconfigure DNS resolution on FreeBSD VMs

- common/coredump_config.jl
- common/mac_launchctl_config.jl
- macos-seatbelt/common.jl
Hopefully fixes https://github.com/JuliaCI/sandboxed-buildkite-agent/issues/86.
Reading the docs I figured that an exit code of 255 would be what happens when killing the agent from the WebUI, but that seems to run into https://github.com/buildkite/agent/issues/3052. Ideally we wouldn't have to use `--disconnect-after-job`, but I don't see another way to safely manage the worker state.
> macOS: Run agent in a loop instead of relying on KeepAlive

- Artifacts.toml
- admin/Manifest.toml
Skipped 3.83 because there seem to be some bugs with artifact uploads.
> Update Buildkite agent to v3.82.1.

- linux-sandbox.jl/common.jl
This should never be wrong (even if it is unnecessary to override in most cases) and will help reduce issues with the `armv7l` buildbots which are actually `aarch64` processors, but are running `armv7l` rootfs images, and thus cannot run `aarch64` programs.
> Override `BUILDKITE_PLUGIN_JULIA_ARCH` with the given `arch`.

- freebsd-kvm/README.md
- freebsd-kvm/base-image/freebsd13.pkr.hcl
Ref https://github.com/JuliaLang/julia/pull/57874#issuecomment-2748690414. As of https://github.com/JuliaPackaging/BinaryBuilderBase.jl/pull/418, Yggdrasil is building for FreeBSD 13.4 on x86-64 rather than 13.2, so we need to update the CI image here so that BinaryBuilder dependencies can be safely upgraded without weird breakages.
@staticfloat, can you help with deploying this once it's merged?
> Update FreeBSD image from 13.2 to 13.4

- windows-kvm/buildkite-worker/Makefile
This will clean out the installed VM images as well.  This is basically how I fixed the `C:/cache` failures
> Windows: Add `distclean` target

- freebsd-kvm/buildkite-worker/setup_scripts/install-buildkite-agent.sh
- macos-seatbelt/common.jl
- windows-kvm/buildkite-worker/setup_scripts/0-04-install-cryptic-secrets.ps1
Counterpart of https://github.com/JuliaCI/cryptic-buildkite-plugin/pull/38, extending https://github.com/JuliaCI/sandboxed-buildkite-agent/pull/105 and https://github.com/JuliaCI/sandboxed-buildkite-agent/pull/106
The fact that we're apparently not using a fixed version of cryptic across CI pipelines (I guess it should be tagged as `v3`, but , means that the above change may result in things breaking until the workers are updated to reflect the corrected naming.
cc @IanButterworth @fredrikekre
> Fix more typos in SECRETS_MOUNT_POINT plugin variables.

- linux-sandbox.jl/common.jl
There's no point to inherit this - we don't map the same filesystem. Ref https://github.com/JuliaLang/julia/pull/59191.
> Set SHELL upon entry to sandbox
